name: lowprofool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - tensorflow
  - keras
  - tqdm
  - openml
  - jupyter